version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Pruthuvi@123"
      ACCEPT_EULA: "Y"
    # healthcheck:
    #   test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Pruthuvi@123", "-Q", "SELECT 1" ]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5241:8080"
    depends_on:
      - sqlserver
      # sqlserver:
      #   condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
